ugraded to Camunda EE 7.13.0 added h2 dependency added spring-boot-starter-data-jpa dependency due to java.lang.NoClassDefFoundError: javax/activation/DataSource in Java 11 removed undertow dependency